#!/bin/sh

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
grey='\033[0m'

errors=false

echo "${green}Running Git pre-commit hook...\n${grey}"

# Arguments [type, files, linter_command, linter_options]
check_files_with_linter () {
  echo "${green}[$1 Style][Info]: Checking $1 style with $3${grey}"

  if [ -n "$2" ]; then
    echo "${green}[$1 Style][Info]: Files to check:\n${blue}$2${grey}"

    # Run linter for passed files
    bundle exec $3 $4 $2

    if [ $? -ne 0 ]; then
      echo "${red}[$1 Style][Error]: Please, fix the issues and commit again\n${grey}"
      errors=true
    else
      echo "${green}[$1 Style][Info]: Checking passed\n"
    fi
  else
    echo "${green}[$1 Style][Info]: No files to check\n${grey}"
  fi
}


# Slim-lint

# Check if slim-lint is installed for the current project
if bundle exec slim-lint -v >/dev/null 2>&1; then
  # Check config file existence
  if [ ! -f '.slim-lint.yml' ]; then
    echo "${yellow}[Slim Style][Warning]: No .slim-lint.yml config file.${grey}"
  fi

  # Get only the staged slim files
  slim_files="$(git diff --cached --name-only --diff-filter=AMC app/views/)"

  check_files_with_linter "Slim" "$slim_files" "slim-lint"
else
  echo >&2 "${red}[Slim Style][Fatal]: Please, add 'slim_lint' gem to Gemfile\n${grey}"
  errors=true
fi


# # JSHint
#
# # Check if JSHint is installed
# if bundle exec jshint -v >/dev/null 2>&1; then
#   # Check config file existence
#   if [ ! -f '.jshintrc' ]; then
#     echo "${yellow}[Javascript Style][Warning]: No .jshintrc config file.${grey}"
#   fi
#
#   # Get only the staged javascript files
#   js_files="$(git diff --cached --name-only --diff-filter=AMC app/assets/javascripts/)"
#
#   check_files_with_linter "Javascript" "$js_files" "jshint"
# else
#   echo >&2 "${red}[Javascript Style][Fatal]: Please, install 'jshint' via npm\n${grey}"
#   errors=true
# fi


# Coffeelint

# Check if Coffelint is installed
if bundle exec coffeelint -v >/dev/null 2>&1; then
  # Check config file existence
  if [ ! -f '.coffeelint.json' ]; then
    echo "${yellow}[Coffeescript Style][Warning]: No .coffeelint.json config file.${grey}"
  fi

  # Get only the staged coffeescript files
  coffee_files="$(git diff --cached --name-only --diff-filter=AMC app/assets/javascripts/)"

  check_files_with_linter "Coffeescript" "$coffee_files" "coffeelint"
else
  echo >&2 "${red}[Coffeescript Style][Fatal]: Please, install 'coffeelint' via npm or add 'coffeelint' gem to Gemfile\n${grey}"
  errors=true
fi


# Rubocop

# Check if Rubocop is installed for the current project
if bundle exec rubocop -v >/dev/null 2>&1; then
  # Check config file existence
  if [ ! -f '.rubocop.yml' ]; then
    echo "${yellow}[Ruby Style][Warning]: No .rubocop.yml config file.${grey}"
  fi

  # Get only the staged files
  files="$(git diff --cached --name-only --diff-filter=AMC -- . ':!app/assets/' ':!app/views/')"

  check_files_with_linter  "Ruby" "$files" "rubocop" "--force-exclusion"
else
  echo >&2 "${red}[Ruby Style][Fatal]: Please, add 'rubocop' gem to Gemfile\n${grey}"
  errors=true
fi

if [ "$errors" = true ]; then
  exit 1
fi

exit 0
